- name: Configure ArgoCD Applications
  hosts: control-plane
  become: yes
  vars:
    argocd_apps_repo: "https://github.com/soldatviktimnosti/infra-apps.git"
  tasks:
    - name: Wait for ArgoCD API
      uri:
        url: "http://localhost:30007/api/v1/health"
        method: GET
        status_code: 200
      register: argocd_health
      retries: 10
      delay: 15
      until: argocd_health.status == 200

    - name: Create ArgoCD Application
      shell: |
        argocd app create infra-apps \
          --repo {{ argocd_apps_repo }} \
          --path "apps/" \
          --dest-server https://kubernetes.default.svc \
          --dest-namespace default \
          --sync-policy automated \
          --auto-prune \
          --self-heal
      environment:
        KUBECONFIG: "/home/vagrant/.kube/config"
        ARGOCD_SERVER: "localhost:30007"
        ARGOCD_AUTH_TOKEN: "{{ argocd_admin_token }}"