- name: Install common dependencies
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install required packages
      apt:
        name: [curl, wget, git, net-tools]
        state: present
  

- name: Configure K3s master
  hosts: control-plane
  become: yes
  vars:
    k3s_master_ip: "192.168.56.101"
    kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
    k3s_version: "v1.33.1+k3s1" 
  
  tasks:
    - name: Install K3s server with fixed IP
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -s - \
          --write-kubeconfig-mode 644 \
          --disable traefik \
          --node-name k3s-master \
          --tls-san {{ k3s_master_ip }} \
          --bind-address {{ k3s_master_ip }} \
          --advertise-address {{ k3s_master_ip }}
      args:
        creates: "/usr/local/bin/k3s"
    
    - name: Verify K3s service
      command: systemctl is-active k3s
      register: k3s_status
      until: k3s_status.rc == 0
      retries: 10
      delay: 5

    - name: Copy kubeconfig
      become: yes
      shell: |
        mkdir -p /home/vagrant/.kube && \
        cp {{ kubeconfig_path }} /home/vagrant/.kube/config && \
        chown vagrant:vagrant /home/vagrant/.kube/config
      args:
        creates: "/home/vagrant/.kube/config"

- name: Deep API health check
  hosts: control-plane
  tasks:
    - name: Check Kubernetes components status
      command: sudo k3s kubectl get cs
      register: components_status
      until: "'Healthy' in components_status.stdout"
      retries: 15
      delay: 15
      ignore_errors: yes

    - name: Direct port check
      wait_for:
        host: "127.0.0.1"
        port: 6443
        timeout: 60
      delegate_to: "{{ groups['control-plane'][0] }}"

    - name: Verify API with admin credentials
      shell: |
        sudo k3s kubectl get --raw='/healthz?verbose'
      register: api_health_raw
      changed_when: false
      retries: 10
      delay: 10

    - name: Show full API debug info
      debug:
        msg: |
          API STATUS DEBUG:
          Components: {{ components_status.stdout }}
          Raw API Check: {{ api_health_raw.stdout }}
          K3s Service: {{ lookup('pipe', 'sudo systemctl status k3s') }}
          Containers: {{ lookup('pipe', 'sudo crictl ps -a') }}
      when: api_health_raw.rc != 0

- name: Configure workers
  hosts: workers
  become: yes
  vars:
    k3s_master_ip: "192.168.56.101"
    kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
    k3s_version: "v1.33.1+k3s1"

  tasks:
    - name: Get master node token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      delegate_to: "{{ groups['control-plane'][0] }}"
    
    - name: Install K3s agent
      shell: |
        curl -sfL https://get.k3s.io | \
          K3S_URL=https://{{ k3s_master_ip }}:6443 \
          K3S_TOKEN={{ k3s_token.stdout }} \
          INSTALL_K3S_VERSION={{ k3s_version }} \
          sh -s - --node-name k3s-worker-{{ ansible_hostname }}
      args:
        creates: "/usr/local/bin/k3s"
    
    - name: Verify agent status
      command: systemctl is-active k3s-agent
      register: agent_status
      until: agent_status.rc == 0
      retries: 10
      delay: 5

- name: Verify cluster
  hosts: control-plane
  become: yes
  vars:
    k3s_master_ip: "192.168.56.101"
    kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
    k3s_version: "v1.33.1+k3s1"

  tasks:
    - name: Check nodes status
      command: kubectl get nodes
      register: nodes
      until: "'k3s-master' in nodes.stdout and 'k3s-worker' in nodes.stdout"
      retries: 10
      delay: 15

- name: Install ArgoCD on master
  hosts: control-plane
  become: yes
  vars:
    k3s_master_ip: "192.168.56.101"
    kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
    k3s_version: "v1.33.1+k3s1"

  tasks:
    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: "/usr/local/bin/helm"
    
    - name: Check if ArgoCD already installed
      become: yes
      shell: |
        helm status argocd -n argocd >/dev/null 2>&1 && echo "installed" || echo "not_installed"
      register: argocd_status
      environment:
      KUBECONFIG: "/home/vagrant/.kube/config"
      changed_when: false

    - name: Deploy ArgoCD
      become: yes
      shell: |
        helm repo add argo https://argoproj.github.io/argo-helm
        helm repo update
        helm upgrade --install argocd argo/argo-cd \
          --namespace argocd \
          --create-namespace \
          --set server.service.type=NodePort \
          --set server.service.nodePort=30007 \
          --set server.extraArgs[0]=--insecure
      environment:
      KUBECONFIG: "/home/vagrant/.kube/config"
      when: argocd_status.stdout == "not_installed"
    
    - name: Wait for ArgoCD initial admin secret to be created
      shell: kubectl -n argocd get secret argocd-initial-admin-secret --no-headers
      register: secret_check
      retries: 10
      delay: 15
      until: secret_check.rc == 0
      changed_when: false
      environment:
      KUBECONFIG: "/home/vagrant/.kube/config"
    
    - name: Get ArgoCD password
      become: yes
      shell: |
        kubectl -n argocd get secret argocd-initial-admin-secret \
          -o jsonpath='{.data.password}' | base64 -d || echo "PASSWORD_NOT_READY"
      register: argocd_password
      retries: 10
      delay: 15
      until: argocd_password.stdout != "PASSWORD_NOT_READY"
      changed_when: false
      environment:
      KUBECONFIG: "/home/vagrant/.kube/config"

    - name: Show access info
      debug:
        msg: |
          ArgoCD доступен по адресу:
          http://{{ k3s_master_ip }}:30007
          Логин: admin
          Пароль: {{ argocd_password.stdout }}
     

    - name: Debug ArgoCD password raw output
      debug:
        var: argocd_password
      "

    - name: Show ArgoCD access information
      debug:
        msg: |
          ArgoCD доступен по адресу:
          http://192.168.56.101:30007
          Логин: admin
          Пароль: {{ argocd_password.stdout }}
    

    - name: Show current user
      shell: whoami
      register: current_user

    - debug:
        var: current_user.stdout

    - name: Show KUBECONFIG env
      shell: echo $KUBECONFIG
      environment:
      KUBECONFIG: "/home/vagrant/.kube/config"
      register: kubeconfig_path

    - debug:
        var: kubeconfig_path.stdout

